
Plugin 'tpope/vim-pathogen'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-cucumber'
Plugin 'tpope/vim-markdown'
Plugin 'scrooloose/nerdtree'
Plugin 'corntrace/bufexplorer'
Plugin 'ervandew/supertab'
Plugin 'dalibor/snipmate.vim'
Plugin 'dalibor/snipmate-snippets'
Plugin 'vim-ruby/vim-ruby'
Plugin 'mileszs/ack.vim'
Plugin 'altercation/vim-colors-solarized.git'
Plugin 'kien/ctrlp.vim'
Plugin 'benmills/vimux'
Plugin 'skalnik/vim-vroom'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'tpope/vim-ragtag'
Plugin 'pangloss/vim-javascript'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'godlygeek/tabular'


