
"Plug 'vim-scripts/jsonvim'
"Plug 'vim-scripts/Enhanced-Javascript-syntax'
"Plug 'vim-scripts/JSON.vim'
Plug 'vim-scripts/JavaScript-syntax-add-E4X-support'
"Plug 'vim-scripts/Javascript-OmniCompletion-with-YUI-and-j'
"Plug 'vim-scripts/jQuery'
Plug 'jamescarr/snipmate-nodejs'
"Plug 'myhere/vim-nodejs-complete'
"Plug 'vim-scripts/node.js'
Plug 'ternjs/tern_for_vim'
"Plug 'vim-scripts/vim-jsbeautify'
"Plug 'walm/jshint.vim'
