
"Plugin 'jsonvim'
Plugin 'Enhanced-Javascript-syntax'
Plugin 'JSON.vim'
Plugin 'JavaScript-syntax-add-E4X-support'
Plugin 'Javascript-OmniCompletion-with-YUI-and-j'
Plugin 'jQuery'
Plugin 'jamescarr/snipmate-nodejs'
Plugin 'myhere/vim-nodejs-complete'
Plugin 'node.js'
Plugin 'ternjs/tern_for_vim'
Plugin 'vim-jsbeautify'
Plugin 'walm/jshint.vim'
