imap <C-1> <C-O>1tabnext
nmap <C-1> 1tabnext
imap <C-2> <C-O>2tabnext
nmap <C-2> 2tabnext
imap <C-3> <C-O>3tabnext
nmap <C-3> 3tabnext
imap <C-4> <C-O>4tabnext
nmap <C-4> 4tabnext
imap <C-5> <C-O>5tabnext
nmap <C-5> 5tabnext
imap <C-6> <C-O>6tabnext
nmap <C-6> 6tabnext
imap <C-7> <C-O>7tabnext
nmap <C-7> 7tabnext
imap <C-8> <C-O>8tabnext
nmap <C-8> 8tabnext
imap <C-9> <C-O>9tabnext
nmap <C-9> 9tabnext
