imap <C-1> <C-O>:1tabnext<cr>
imap <C-2> <C-O>:2tabnext<cr>
imap <C-3> <C-O>:3tabnext<cr>
imap <C-4> <C-O>:4tabnext<cr>
imap <C-5> <C-O>:5tabnext<cr>
imap <C-6> <C-O>:6tabnext<cr>
imap <C-7> <C-O>:7tabnext<cr>
imap <C-8> <C-O>:8tabnext<cr>
imap <C-9> <C-O>:9tabnext<cr>

nmap <C-1> :1tabnext<cr>
nmap <C-2> :2tabnext<cr>
nmap <C-3> :3tabnext<cr>
nmap <C-4> :4tabnext<cr>
nmap <C-5> :5tabnext<cr>
nmap <C-6> :6tabnext<cr>
nmap <C-7> :7tabnext<cr>
nmap <C-8> :8tabnext<cr>
nmap <C-9> :9tabnext<cr>
